/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedTrilhasRouteImport } from './routes/_authenticated/trilhas'
import { Route as AuthenticatedPerfilRouteImport } from './routes/_authenticated/perfil'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedConcursosRouteImport } from './routes/_authenticated/concursos'
import { Route as AuthenticatedAssinaturaBloqueadaRouteImport } from './routes/_authenticated/assinatura-bloqueada'
import { Route as AuthenticatedAcervoRouteImport } from './routes/_authenticated/acervo'
import { Route as AuthenticatedAdminUsuariosRouteImport } from './routes/_authenticated/admin/usuarios'
import { Route as AuthenticatedAdminTrilhasRouteImport } from './routes/_authenticated/admin/trilhas'
import { Route as AuthenticatedAdminQuestoesRouteImport } from './routes/_authenticated/admin/questoes'
import { Route as AuthenticatedAdminNoticiasRouteImport } from './routes/_authenticated/admin/noticias'
import { Route as AuthenticatedAdminDashboardRouteImport } from './routes/_authenticated/admin/dashboard'
import { Route as AuthenticatedAdminConfiguracoesRouteImport } from './routes/_authenticated/admin/configuracoes'
import { Route as AuthenticatedAdminConcursosRouteImport } from './routes/_authenticated/admin/concursos'
import { Route as AuthenticatedAdminAcervoRouteImport } from './routes/_authenticated/admin/acervo'
import { Route as ApiPublicHotmartWebhookRouteImport } from './routes/api/public/hotmart/webhook'
import { Route as AuthenticatedMateriaisMaterialIdQuestoesRouteImport } from './routes/_authenticated/materiais.$materialId.questoes'
import { Route as AuthenticatedMateriaisMaterialIdPdfRouteImport } from './routes/_authenticated/materiais.$materialId.pdf'
import { Route as AuthenticatedMateriaisMaterialIdDesempenhoRouteImport } from './routes/_authenticated/materiais.$materialId.desempenho'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTrilhasRoute = AuthenticatedTrilhasRouteImport.update({
  id: '/trilhas',
  path: '/trilhas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPerfilRoute = AuthenticatedPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedConcursosRoute = AuthenticatedConcursosRouteImport.update({
  id: '/concursos',
  path: '/concursos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAssinaturaBloqueadaRoute =
  AuthenticatedAssinaturaBloqueadaRouteImport.update({
    id: '/assinatura-bloqueada',
    path: '/assinatura-bloqueada',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAcervoRoute = AuthenticatedAcervoRouteImport.update({
  id: '/acervo',
  path: '/acervo',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminUsuariosRoute =
  AuthenticatedAdminUsuariosRouteImport.update({
    id: '/admin/usuarios',
    path: '/admin/usuarios',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminTrilhasRoute =
  AuthenticatedAdminTrilhasRouteImport.update({
    id: '/admin/trilhas',
    path: '/admin/trilhas',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminQuestoesRoute =
  AuthenticatedAdminQuestoesRouteImport.update({
    id: '/admin/questoes',
    path: '/admin/questoes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminNoticiasRoute =
  AuthenticatedAdminNoticiasRouteImport.update({
    id: '/admin/noticias',
    path: '/admin/noticias',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminDashboardRoute =
  AuthenticatedAdminDashboardRouteImport.update({
    id: '/admin/dashboard',
    path: '/admin/dashboard',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminConfiguracoesRoute =
  AuthenticatedAdminConfiguracoesRouteImport.update({
    id: '/admin/configuracoes',
    path: '/admin/configuracoes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminConcursosRoute =
  AuthenticatedAdminConcursosRouteImport.update({
    id: '/admin/concursos',
    path: '/admin/concursos',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminAcervoRoute =
  AuthenticatedAdminAcervoRouteImport.update({
    id: '/admin/acervo',
    path: '/admin/acervo',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiPublicHotmartWebhookRoute = ApiPublicHotmartWebhookRouteImport.update({
  id: '/api/public/hotmart/webhook',
  path: '/api/public/hotmart/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedMateriaisMaterialIdQuestoesRoute =
  AuthenticatedMateriaisMaterialIdQuestoesRouteImport.update({
    id: '/materiais/$materialId/questoes',
    path: '/materiais/$materialId/questoes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMateriaisMaterialIdPdfRoute =
  AuthenticatedMateriaisMaterialIdPdfRouteImport.update({
    id: '/materiais/$materialId/pdf',
    path: '/materiais/$materialId/pdf',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMateriaisMaterialIdDesempenhoRoute =
  AuthenticatedMateriaisMaterialIdDesempenhoRouteImport.update({
    id: '/materiais/$materialId/desempenho',
    path: '/materiais/$materialId/desempenho',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/acervo': typeof AuthenticatedAcervoRoute
  '/assinatura-bloqueada': typeof AuthenticatedAssinaturaBloqueadaRoute
  '/concursos': typeof AuthenticatedConcursosRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/perfil': typeof AuthenticatedPerfilRoute
  '/trilhas': typeof AuthenticatedTrilhasRoute
  '/admin/acervo': typeof AuthenticatedAdminAcervoRoute
  '/admin/concursos': typeof AuthenticatedAdminConcursosRoute
  '/admin/configuracoes': typeof AuthenticatedAdminConfiguracoesRoute
  '/admin/dashboard': typeof AuthenticatedAdminDashboardRoute
  '/admin/noticias': typeof AuthenticatedAdminNoticiasRoute
  '/admin/questoes': typeof AuthenticatedAdminQuestoesRoute
  '/admin/trilhas': typeof AuthenticatedAdminTrilhasRoute
  '/admin/usuarios': typeof AuthenticatedAdminUsuariosRoute
  '/materiais/$materialId/desempenho': typeof AuthenticatedMateriaisMaterialIdDesempenhoRoute
  '/materiais/$materialId/pdf': typeof AuthenticatedMateriaisMaterialIdPdfRoute
  '/materiais/$materialId/questoes': typeof AuthenticatedMateriaisMaterialIdQuestoesRoute
  '/api/public/hotmart/webhook': typeof ApiPublicHotmartWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/acervo': typeof AuthenticatedAcervoRoute
  '/assinatura-bloqueada': typeof AuthenticatedAssinaturaBloqueadaRoute
  '/concursos': typeof AuthenticatedConcursosRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/perfil': typeof AuthenticatedPerfilRoute
  '/trilhas': typeof AuthenticatedTrilhasRoute
  '/admin/acervo': typeof AuthenticatedAdminAcervoRoute
  '/admin/concursos': typeof AuthenticatedAdminConcursosRoute
  '/admin/configuracoes': typeof AuthenticatedAdminConfiguracoesRoute
  '/admin/dashboard': typeof AuthenticatedAdminDashboardRoute
  '/admin/noticias': typeof AuthenticatedAdminNoticiasRoute
  '/admin/questoes': typeof AuthenticatedAdminQuestoesRoute
  '/admin/trilhas': typeof AuthenticatedAdminTrilhasRoute
  '/admin/usuarios': typeof AuthenticatedAdminUsuariosRoute
  '/materiais/$materialId/desempenho': typeof AuthenticatedMateriaisMaterialIdDesempenhoRoute
  '/materiais/$materialId/pdf': typeof AuthenticatedMateriaisMaterialIdPdfRoute
  '/materiais/$materialId/questoes': typeof AuthenticatedMateriaisMaterialIdQuestoesRoute
  '/api/public/hotmart/webhook': typeof ApiPublicHotmartWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/acervo': typeof AuthenticatedAcervoRoute
  '/_authenticated/assinatura-bloqueada': typeof AuthenticatedAssinaturaBloqueadaRoute
  '/_authenticated/concursos': typeof AuthenticatedConcursosRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/perfil': typeof AuthenticatedPerfilRoute
  '/_authenticated/trilhas': typeof AuthenticatedTrilhasRoute
  '/_authenticated/admin/acervo': typeof AuthenticatedAdminAcervoRoute
  '/_authenticated/admin/concursos': typeof AuthenticatedAdminConcursosRoute
  '/_authenticated/admin/configuracoes': typeof AuthenticatedAdminConfiguracoesRoute
  '/_authenticated/admin/dashboard': typeof AuthenticatedAdminDashboardRoute
  '/_authenticated/admin/noticias': typeof AuthenticatedAdminNoticiasRoute
  '/_authenticated/admin/questoes': typeof AuthenticatedAdminQuestoesRoute
  '/_authenticated/admin/trilhas': typeof AuthenticatedAdminTrilhasRoute
  '/_authenticated/admin/usuarios': typeof AuthenticatedAdminUsuariosRoute
  '/_authenticated/materiais/$materialId/desempenho': typeof AuthenticatedMateriaisMaterialIdDesempenhoRoute
  '/_authenticated/materiais/$materialId/pdf': typeof AuthenticatedMateriaisMaterialIdPdfRoute
  '/_authenticated/materiais/$materialId/questoes': typeof AuthenticatedMateriaisMaterialIdQuestoesRoute
  '/api/public/hotmart/webhook': typeof ApiPublicHotmartWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/acervo'
    | '/assinatura-bloqueada'
    | '/concursos'
    | '/dashboard'
    | '/perfil'
    | '/trilhas'
    | '/admin/acervo'
    | '/admin/concursos'
    | '/admin/configuracoes'
    | '/admin/dashboard'
    | '/admin/noticias'
    | '/admin/questoes'
    | '/admin/trilhas'
    | '/admin/usuarios'
    | '/materiais/$materialId/desempenho'
    | '/materiais/$materialId/pdf'
    | '/materiais/$materialId/questoes'
    | '/api/public/hotmart/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/acervo'
    | '/assinatura-bloqueada'
    | '/concursos'
    | '/dashboard'
    | '/perfil'
    | '/trilhas'
    | '/admin/acervo'
    | '/admin/concursos'
    | '/admin/configuracoes'
    | '/admin/dashboard'
    | '/admin/noticias'
    | '/admin/questoes'
    | '/admin/trilhas'
    | '/admin/usuarios'
    | '/materiais/$materialId/desempenho'
    | '/materiais/$materialId/pdf'
    | '/materiais/$materialId/questoes'
    | '/api/public/hotmart/webhook'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/reset-password'
    | '/_authenticated/acervo'
    | '/_authenticated/assinatura-bloqueada'
    | '/_authenticated/concursos'
    | '/_authenticated/dashboard'
    | '/_authenticated/perfil'
    | '/_authenticated/trilhas'
    | '/_authenticated/admin/acervo'
    | '/_authenticated/admin/concursos'
    | '/_authenticated/admin/configuracoes'
    | '/_authenticated/admin/dashboard'
    | '/_authenticated/admin/noticias'
    | '/_authenticated/admin/questoes'
    | '/_authenticated/admin/trilhas'
    | '/_authenticated/admin/usuarios'
    | '/_authenticated/materiais/$materialId/desempenho'
    | '/_authenticated/materiais/$materialId/pdf'
    | '/_authenticated/materiais/$materialId/questoes'
    | '/api/public/hotmart/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ApiPublicHotmartWebhookRoute: typeof ApiPublicHotmartWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/trilhas': {
      id: '/_authenticated/trilhas'
      path: '/trilhas'
      fullPath: '/trilhas'
      preLoaderRoute: typeof AuthenticatedTrilhasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/perfil': {
      id: '/_authenticated/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof AuthenticatedPerfilRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/concursos': {
      id: '/_authenticated/concursos'
      path: '/concursos'
      fullPath: '/concursos'
      preLoaderRoute: typeof AuthenticatedConcursosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/assinatura-bloqueada': {
      id: '/_authenticated/assinatura-bloqueada'
      path: '/assinatura-bloqueada'
      fullPath: '/assinatura-bloqueada'
      preLoaderRoute: typeof AuthenticatedAssinaturaBloqueadaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/acervo': {
      id: '/_authenticated/acervo'
      path: '/acervo'
      fullPath: '/acervo'
      preLoaderRoute: typeof AuthenticatedAcervoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/usuarios': {
      id: '/_authenticated/admin/usuarios'
      path: '/admin/usuarios'
      fullPath: '/admin/usuarios'
      preLoaderRoute: typeof AuthenticatedAdminUsuariosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/trilhas': {
      id: '/_authenticated/admin/trilhas'
      path: '/admin/trilhas'
      fullPath: '/admin/trilhas'
      preLoaderRoute: typeof AuthenticatedAdminTrilhasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/questoes': {
      id: '/_authenticated/admin/questoes'
      path: '/admin/questoes'
      fullPath: '/admin/questoes'
      preLoaderRoute: typeof AuthenticatedAdminQuestoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/noticias': {
      id: '/_authenticated/admin/noticias'
      path: '/admin/noticias'
      fullPath: '/admin/noticias'
      preLoaderRoute: typeof AuthenticatedAdminNoticiasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/dashboard': {
      id: '/_authenticated/admin/dashboard'
      path: '/admin/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AuthenticatedAdminDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/configuracoes': {
      id: '/_authenticated/admin/configuracoes'
      path: '/admin/configuracoes'
      fullPath: '/admin/configuracoes'
      preLoaderRoute: typeof AuthenticatedAdminConfiguracoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/concursos': {
      id: '/_authenticated/admin/concursos'
      path: '/admin/concursos'
      fullPath: '/admin/concursos'
      preLoaderRoute: typeof AuthenticatedAdminConcursosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/acervo': {
      id: '/_authenticated/admin/acervo'
      path: '/admin/acervo'
      fullPath: '/admin/acervo'
      preLoaderRoute: typeof AuthenticatedAdminAcervoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/hotmart/webhook': {
      id: '/api/public/hotmart/webhook'
      path: '/api/public/hotmart/webhook'
      fullPath: '/api/public/hotmart/webhook'
      preLoaderRoute: typeof ApiPublicHotmartWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/materiais/$materialId/questoes': {
      id: '/_authenticated/materiais/$materialId/questoes'
      path: '/materiais/$materialId/questoes'
      fullPath: '/materiais/$materialId/questoes'
      preLoaderRoute: typeof AuthenticatedMateriaisMaterialIdQuestoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/materiais/$materialId/pdf': {
      id: '/_authenticated/materiais/$materialId/pdf'
      path: '/materiais/$materialId/pdf'
      fullPath: '/materiais/$materialId/pdf'
      preLoaderRoute: typeof AuthenticatedMateriaisMaterialIdPdfRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/materiais/$materialId/desempenho': {
      id: '/_authenticated/materiais/$materialId/desempenho'
      path: '/materiais/$materialId/desempenho'
      fullPath: '/materiais/$materialId/desempenho'
      preLoaderRoute: typeof AuthenticatedMateriaisMaterialIdDesempenhoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAcervoRoute: typeof AuthenticatedAcervoRoute
  AuthenticatedAssinaturaBloqueadaRoute: typeof AuthenticatedAssinaturaBloqueadaRoute
  AuthenticatedConcursosRoute: typeof AuthenticatedConcursosRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedPerfilRoute: typeof AuthenticatedPerfilRoute
  AuthenticatedTrilhasRoute: typeof AuthenticatedTrilhasRoute
  AuthenticatedAdminAcervoRoute: typeof AuthenticatedAdminAcervoRoute
  AuthenticatedAdminConcursosRoute: typeof AuthenticatedAdminConcursosRoute
  AuthenticatedAdminConfiguracoesRoute: typeof AuthenticatedAdminConfiguracoesRoute
  AuthenticatedAdminDashboardRoute: typeof AuthenticatedAdminDashboardRoute
  AuthenticatedAdminNoticiasRoute: typeof AuthenticatedAdminNoticiasRoute
  AuthenticatedAdminQuestoesRoute: typeof AuthenticatedAdminQuestoesRoute
  AuthenticatedAdminTrilhasRoute: typeof AuthenticatedAdminTrilhasRoute
  AuthenticatedAdminUsuariosRoute: typeof AuthenticatedAdminUsuariosRoute
  AuthenticatedMateriaisMaterialIdDesempenhoRoute: typeof AuthenticatedMateriaisMaterialIdDesempenhoRoute
  AuthenticatedMateriaisMaterialIdPdfRoute: typeof AuthenticatedMateriaisMaterialIdPdfRoute
  AuthenticatedMateriaisMaterialIdQuestoesRoute: typeof AuthenticatedMateriaisMaterialIdQuestoesRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAcervoRoute: AuthenticatedAcervoRoute,
  AuthenticatedAssinaturaBloqueadaRoute: AuthenticatedAssinaturaBloqueadaRoute,
  AuthenticatedConcursosRoute: AuthenticatedConcursosRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedPerfilRoute: AuthenticatedPerfilRoute,
  AuthenticatedTrilhasRoute: AuthenticatedTrilhasRoute,
  AuthenticatedAdminAcervoRoute: AuthenticatedAdminAcervoRoute,
  AuthenticatedAdminConcursosRoute: AuthenticatedAdminConcursosRoute,
  AuthenticatedAdminConfiguracoesRoute: AuthenticatedAdminConfiguracoesRoute,
  AuthenticatedAdminDashboardRoute: AuthenticatedAdminDashboardRoute,
  AuthenticatedAdminNoticiasRoute: AuthenticatedAdminNoticiasRoute,
  AuthenticatedAdminQuestoesRoute: AuthenticatedAdminQuestoesRoute,
  AuthenticatedAdminTrilhasRoute: AuthenticatedAdminTrilhasRoute,
  AuthenticatedAdminUsuariosRoute: AuthenticatedAdminUsuariosRoute,
  AuthenticatedMateriaisMaterialIdDesempenhoRoute:
    AuthenticatedMateriaisMaterialIdDesempenhoRoute,
  AuthenticatedMateriaisMaterialIdPdfRoute:
    AuthenticatedMateriaisMaterialIdPdfRoute,
  AuthenticatedMateriaisMaterialIdQuestoesRoute:
    AuthenticatedMateriaisMaterialIdQuestoesRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ApiPublicHotmartWebhookRoute: ApiPublicHotmartWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
